# Static checks and tests for the infrastructure definition logic.

permissions: {} # default to no permissions, set at the per-job level

on:
  push:
    branches: [ master ]
  pull_request:
    paths:
      - ".github/workflows/infrastructure.yml"
      - "infrastructure/**"
  workflow_call:
  workflow_dispatch:

name: infrastructure
jobs:

  lint:
    permissions:
      contents: read # allows repository content checkout
    runs-on: ubuntu-latest
    defaults:
      run: { working-directory: infrastructure }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - run: pip install '.[dev]'
      - run: python -m ruff check .

  typecheck:
    permissions:
      contents: read # allows repository content checkout
    runs-on: ubuntu-latest
    defaults:
      run: { working-directory: infrastructure }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - run: pip install '.[dev]'
      - run: python -m pyright .

  test:
    permissions:
      contents: read # allows repository content checkout
    runs-on: ubuntu-latest
    defaults:
      run: { working-directory: infrastructure }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - run: pip install '.[dev]'
      - run: python -m pytest . --verbose --color=yes
